package com.example.coin_panion.classes;

import android.widget.Toast;

import java.sql.Blob;
import java.sql.ResultSet;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class User{

//    /*User info for account*/
//    private static Integer account_ID;
//    private String mobile_number;
//    private String first_name;
//    private String last_name;
//    private String username;
//    private String password;
//
//    /*User additional info*/
//    private Blob profile_pic;
//    private String user_bio;
//
//    private DebtLimit user_debtLimit;
//
//    /*Retrieve user from database*/
//    public User(String mobileNumber) {
//        // TODO query from database to retrieve user info based on mobile number
//        getUserData(mobileNumber);
//    }
//
//
//
//    /*Create new user object*/
//    public User(String mobileNumber, String fullName, String userName, Blob profilePic, String password, String email) {
//        // TODO User ID is the mobile phone number / generated by database
//        this.mobileNumber = mobileNumber;
//        this.fullName = fullName;
//        this.userName = userName;
//        this.email = email;
//        // TODO Profile pic will be set with default one initially
//        this.profilePic = profilePic;
//        this.password = password;
//
//    }
//
//    /* TODO Insert user info into database*/
//    public User(String mobileNumber, String email, String fullName, String userName, String password) {
//        this.mobileNumber = mobileNumber;
//        this.email = email;
//        this.fullName = fullName;
//        this.userName = userName;
//        this.password = password;
//    }
//
//    /*All setters*/
//    public void Password(String password){
//        if(password!=null)
//            this.password.equals(password);
//    }
//
//
//    public void updateEmail(String email){
//        if(email!=null)
//            this.email = email;
//    }
//
//    /*User friend*/
//    private List<Friend> friends;
//
//    /*User notification & activity*/
//    private List<Notification> notifications;
//
//    /*Payment request*/
//    private List<PaymentRequest> paymentRequests;
//
//    public String getUserName() {
//        return userName;
//    }
//
//    public Blob getProfilePic() {
//        return profilePic;
//    }
//
//    public String getPassword() {
//        return password;
//    }
//
//    }
//
//    /*TODO Delete user info database based on this.variable*/
//    public void deleteUser(){
//
//    }
//
//    private ResultSet fetchUserData(String phoneNumber){
//        Integer userID = null;
//        Thread dataThread = new Thread(() -> {
//            // TODO QUERY USER INFO
//        });
//        dataThread.start();
//        while(dataThread.isAlive()){
//
//        }
//        System.setProperty("userID", userID.toString());
//        return null; //TODO CHANGE TO RESULTSET LATER
//    }
//
//    public void fetchGeneralNotification(){
//        Notification notification = new Notification(account_ID);
//        this.notifications = new ArrayList<>(notification.fetchGeneralNotification());
////        String[] notifications = new String[] {
////                "Notification 1",
////                "Notification 2",
////                "Notification 3"
////        };
////        ArrayAdapter<String> adapter = new ArrayAdapter<>(this, R.layout.list_item, notifications);
////        ListView listView = findViewById(R.id.list_view);
////        listView.setAdapter(adapter);
//
//    }
//
//    public List<Notification> getNotifications() {
//        return notifications;
//    }
//
//    public void fetchGeneralPaymentRequest(){
//        PaymentRequest paymentRequest = new PaymentRequest(account_ID);
//        this.paymentRequests = new ArrayList<>(paymentRequest.retrieveAllPaymentRequest());
//    }
//
//    public List<PaymentRequest> getPaymentRequests() {
//        return paymentRequests;
//    }
//
//    public void setSettleUp(String accountName, long accountNumber, Blob qrCode){
//        user_paymentMethod = new SettleUp(account_ID,accountName,accountNumber,qrCode);
//        user_paymentMethod.updateSettleUpInfo();
//    }
//
//    public SettleUp getUser_paymentMethod() {
//        return user_paymentMethod.fetchSettleUp(account_ID);
//    }

}
