package com.example.coin_panion.classes;

import android.widget.Toast;

import java.sql.Blob;
import java.sql.ResultSet;

public class User{

    //TODO generate UserId
    /*User Details*/
    private Integer userID = null;
    private String mobileNumber;
    private String email;
    private String fullName;
    private String userName;
    private Blob profilePic;
    private String password;
    private Thread dataThread;

    /*SettleUp*/
    private SettleUp settleUp;

    /*DebtLimit*/
    private Integer debtLimitAmount;
    private String debtLimitPeriod;

    /*Retrieve user from database*/
    public User(String mobileNumber) {
        // TODO query from database to retrieve user info based on mobile number
        getUserData(mobileNumber);
    }



    /*Create new user object*/
    public User(String mobileNumber, String fullName, String userName, Blob profilePic, String password, String email) {
        // TODO User ID is the mobile phone number / generated by database
        this.mobileNumber = mobileNumber;
        this.fullName = fullName;
        this.userName = userName;
        this.email = email;
        // TODO Profile pic will be set with default one initially
        this.profilePic = profilePic;
        this.password = password;

    }

    /* TODO Insert user info into database*/
    public User(String mobileNumber, String email, String fullName, String userName, String password) {
        this.mobileNumber = mobileNumber;
        this.email = email;
        this.fullName = fullName;
        this.userName = userName;
        this.password = password;
    }

    /*All setters*/
    public void Password(String password){
        if(password!=null)
            this.password.equals(password);
    }


    public void updateEmail(String email){
        if(email!=null)
            this.email = email;
    }

    public void updateProfilePic(Blob newProPic){
        if(newProPic!=null)
            this.profilePic = newProPic;
    }

    public void updateFullName(String newFullName){
        if(newFullName!=null)
            this.fullName = newFullName;
    }

    public void updateUserName(String newUserName){
        if(newUserName!=null)
            this.userName = newUserName;
    }

    public void updatePhoneNumber(String newMobilePhoneNumber){
        if(newMobilePhoneNumber!=null)
            this.mobileNumber = newMobilePhoneNumber;
    }

    /*All getters*/
    public String getMobileNumber() {
        return mobileNumber;
    }

    public String getFullName() {
        return fullName;
    }

    public String getUserName() {
        return userName;
    }

    public Blob getProfilePic() {
        return profilePic;
    }

    public String getPassword() {
        return password;
    }


    /*Query to update user info*/
    public void editUserInfo(String userName, String email, String phoneNumber, String password, Blob userProfileImage){
        updateUserName(userName);
        updateEmail(email);
        updatePhoneNumber(phoneNumber);
        Password(password);
        updateProfilePic(userProfileImage);
        // update query based on this.variable
        String query = this.email + this.userName ;
    }

    /*Query to delete user from database*/
    public void deleteUser() {
        String query = "DELETE FROM `User` " +
                "WHERE userID = " + userID;
    }

    /*Add settleUp for user account*/
    public void addSettleUp(long accountNum, Blob QRCode, String settleup_account_name){
        /*TODO if userID have the accountNum false no need to add*/
        settleUp = new SettleUp(userID, settleup_account_name, accountNum, QRCode);
    }

    /*Update settleUp for user account*/
    public void updateSettleUp(long accountNum, Blob QRCode,  String settleup_account_name){
        /*TODO */
        settleUp.updateSettleUpInformation(settleup_account_name,accountNum,QRCode);
    }

    /*Retrieve existing Settle up*/
    public SettleUp getSettleUp() {
        settleUp = new SettleUp(userID);
        return settleUp;
    }

    private ResultSet getUserData(String phoneNumber){
        Integer userID = null;
        dataThread = new Thread(() ->{
           // TODO QUERY USER INFO
        });
        dataThread.start();
        while(dataThread.isAlive()){

        }
        System.setProperty("userID", userID.toString());
        return null; //TODO CHANGE TO RESULTSET LATER
    }

    /*User set debt limit*/
    public void userSetDebtLimit(Integer debtLimitAmount, String debtLimitPeriod){
        this.debtLimitAmount = debtLimitAmount;
        this.debtLimitPeriod = debtLimitPeriod;

        //TODO update user debtLimit

    }

    public Integer getDebtLimitAmount() {
        return debtLimitAmount;
    }

    public String getDebtLimitPeriod() {
        return debtLimitPeriod;
    }
}
