package com.example.coin_panion.general;

import java.sql.Blob;
import java.util.Objects;

public class User {

    //TODO generate UserId
    final static Integer userID = null;
    private String mobileNumber;
    private String email;
    private String fullName;
    private String userName;
    private Blob profilePic;
    private String password;

    public User() {

    }

    public User(String mobileNumber, String fullName, String userName, Blob profilePic, String password, String email) {
        // TODO User ID is the mobile phone number / generated by database
        this.mobileNumber = mobileNumber;
        this.fullName = fullName;
        this.userName = userName;
        this.email = email;
        // TODO Profile pic will be set with default one initially
        this.profilePic = profilePic;
        this.password = password;
    }

    public boolean confirmPassword(String password){
        return this.password.equals(password);
    }

    public boolean updatePassword(String newPass){
        this.password = newPass;
        return true;
    }

    public boolean updateEmail(String email){
        this.email = email;
        return true;
    }

    public boolean UpdateProfilePic(Blob newProPic){
        this.profilePic = newProPic;
        return true;
    }

    public boolean UpdateFullName(String newFullName){
        this.fullName = newFullName;
        return true;
    }

    public boolean UpdateUserName(String newUserName){
        this.userName = newUserName;
        return true;
    }

    public boolean updatePhoneNumber(String newMobilePhoneNumber){
        this.mobileNumber = newMobilePhoneNumber;
        return true;
    }


    public String getMobileNumber() {
        return mobileNumber;
    }

    public String getFullName() {
        return fullName;
    }

    public String getUserName() {
        return userName;
    }

    public Blob getProfilePic() {
        return profilePic;
    }

    public String getPassword() {
        return password;
    }
}
